### PR TITLE
enable unzip non-utf-8 file

### PR DESCRIPTION
**Pull request by Ghostrick**
I could not unzip the file containing shift-jis. So, I was very sad.
And made it possible.

### CODE REVIEW

**Comment by mhr3** [comment]
Thanks a lot for the patch, unfortunately I'd like to keep the number of dependencies to a minimum, any chance you could change this to use a method similar to what yauzl is doing?

**Comment by Ghostrick** [comment]
A and B contain many source codes.
So, it is not clever to realize on your own.

**Comment by Ghostrick** [comment]
node-iconv and jschardet contain many source codes.
So, it is not clever to realize on your own.

**Comment by mhr3** [comment]
I understand, but would still like to provide reasonable experience without iconv - I added https://github.com/mhr3/unzip-stream/commit/7104e1377381ce6dec1ea419aed0e59b4b9851b5 which can be used to customise the behaviour.

**Pull request closed without merging**
